### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by RigelYoung** [0xb0bb/karkinos#2] opened 2020-07-25 09:19 UTC
when i tried to update the database, something went wrong..

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.6/ssl.py", line 900, in getpeercert
    self._check_connected()
  File "/usr/lib/python3.6/ssl.py", line 864, in _check_connected
    self.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/rigelyoung/.local/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.6/ssl.py", line 900, in getpeercert
    self._check_connected()
  File "/usr/lib/python3.6/ssl.py", line 864, in _check_connected
    self.getpeername()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./kark.py", line 879, in <module>
    main()
  File "./kark.py", line 874, in main
    if not update(True):
  File "./kark.py", line 479, in update
    if not download(url, cwd+'/db/libs.json'):
  File "./kark.py", line 440, in download
    res = requests.head(url, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 98, in head
    return request('head', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

**Comment by 0xb0bb** [comment] 2020-07-25 18:56
Thanks for letting me know. I will be looking into this immediately, however, in the meantime, you can just grab the files in the `/db/` folder here on the repo to manually update.

**Comment by 0xb0bb** [comment] 2020-07-27 21:35
I could not reproduce the issue unfortunately, however it may not have been an issue purely on your side (which is certainly possible) as there were questionable redirects after switching to Github LFS to handle the DBs. I have updated the code accordingly and I believe that should probably clear it up for you so I am closing this. Please update to the latest version of Karkinos.

I will add support to test the internet connection later, but if you have more issues please don't hesitate to open another issue. Thanks for the report, much appreciated.

**Closed as completed by 0xb0bb** 2020-07-27 21:35 UTC
